language: node_js

node_js: 8.4

branches:
  only:
    - master

env:
  matrix:
    - TASK=nojsx
    - TASK=jest
    - TASK=eslint

install:
  - if [ $TASK == jest ];
      then npm i -g yarn@1.3.2;
      yarn install;

    elif [ $TASK = eslint ]; then
      npm install -g
        eslint
        eslint-plugin-promise
        eslint-plugin-standard
        eslint-config-standard
        eslint-config-standard-react
        eslint-config-standard-jsx
        eslint-plugin-react
        eslint-plugin-babel
        babel-eslint
        eslint-plugin-import
        eslint-plugin-node;
    fi

script: ./.travis.script.sh

after_script:
  - if [ $TASK == jest ]; then yarn codecov; fi


notifications:
  email: false
